monolog:
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: error
    critical:
      type: stream
      path: "%kernel.logs_dir%/critical.log"
      level: critical
