version: "3.5"
# https://docs.docker.com/compose/compose-file/compose-versioning/

services:
  sh_recruitment_php:
    container_name: sh_recruitment_php
    restart: always
    build:
      context: .
      dockerfile: docker/build/php/Dockerfile
    ports:
      - "8011:80"
    volumes:
      - .:/var/www/html
      - ./docker/build/php/conf.d/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./docker/build/php/conf.d/docker-php-memlimit.ini:/usr/local/etc/php/conf.d/docker-php-memlimit.ini
    networks:
      - sh_recruitment

networks:
  sh_recruitment:
    name: sh_recruitment
